#!/usr/bin/env -S uv run --script
import os
os.system('uv run --group typing mypy secop_check')
os.system('uv run --group typing pyright secop_check')
os.system('uv run --group typing ty check --output-format concise')
