#!/usr/bin/python3

import sys
from pathlib import Path

from flask import Flask, render_template, request

sys.path.insert(0, str(Path(__file__).absolute().parents[1]))

import secop_check.checker

app = Flask('SECoPCheck', root_path=str(Path(__file__).absolute().parent))


@app.route("/")
def initial():
    return render_template('index.html')


@app.post("/check")
def check():
    checker = secop_check.checker.Checker(version="1.0",
                                          additional=[],
                                          output='none')
    try:
        checker.check(request.form['inputBox'])
    except secop_check.Catastrophe:
        pass
    return render_template('partial/report.html', errors=checker.get_diags())


if __name__ == '__main__':
    host, port = 'localhost', 8000
    app.run(host, port)
